# Generated by Django 3.1 on 2020-12-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockbgimage',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Заголовок'),
        ),
    ]
